%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Script to inspect the simulated RTFs and IRs for one source-reveiver pair from one of the simulated rooms. 
% Loads the .mat file generated by generate_impulse_response.m, picks one source and one receiver, and plots the resulting IR.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear; clc;

room_num = 1;

%% ---- Load the .mat file ----
filename = sprintf('simulated_RTFs/room_0000%d.mat', room_num);
d = load(filename);

% Recombine real + imaginary into complex RTF
% RTF_full is (K_orig, 8, N_rcv)
RTF_full = double(d.RTF_real) + 1j * double(d.RTF_imag);

freqs_orig = double(d.freqs(:));   % (K_orig x 1) — log-spaced
room_dim = d.room_dim(:).';
T60 = double(d.T60);
alpha = double(d.alpha);
source_pos = d.source_pos;
receiver_pos = d.receiver_pos;

K_orig = numel(freqs_orig);
N_src = size(source_pos, 1);
N_rcv = size(receiver_pos, 1);

fprintf('Room: %.2f x %.2f x %.2f m\n', room_dim);
fprintf('T60: %.4f s,  alpha: %.2f\n', T60, alpha);
fprintf('K=%d freq bins (log-spaced %.1f–%.1f Hz), %d sources, %d receivers\n', ...
    K_orig, freqs_orig(1), freqs_orig(end), N_src, N_rcv);

%% ---- Pick one source and one receiver ----
src_idx = 1;
rcv_idx = 100;   % pick any 1..N_rcv

RTF_orig = squeeze(RTF_full(:, src_idx, rcv_idx));  % (K_orig x 1)
rx_pos = receiver_pos(rcv_idx, :);
src_pos = source_pos(src_idx, :);

fprintf('Source pos:   [%.2f, %.2f, %.2f]\n', src_pos);
fprintf('Receiver pos: [%.2f, %.2f, %.2f]\n', rx_pos);

%% ---- Interpolate onto uniform frequency grid for IFFT ----
% Use same Fs and duration as generation script
Fs = 1000;
duration = 1.0;
df = 1 / duration;
freqs_uniform = (0 : df : Fs/2 - df).';  % uniform grid: 0, 1, 2, ... 499 Hz
K = numel(freqs_uniform);

% Interpolate real and imaginary parts separately onto uniform grid
% Frequencies outside the original range get zero (no extrapolation)
RTF_real_interp = interp1(freqs_orig, real(RTF_orig), freqs_uniform, 'pchip', 0);
RTF_imag_interp = interp1(freqs_orig, imag(RTF_orig), freqs_uniform, 'pchip', 0);
RTF = RTF_real_interp + 1j * RTF_imag_interp;

% Zero out bins below the lowest original frequency (no data there)
RTF(freqs_uniform < freqs_orig(1)) = 0;

fprintf('Interpolated to %d uniform bins (df=%.1f Hz)\n', K, df);

%% ---- Time-reverse (as in original script) ----
RTF = conj(RTF);

%% ---- Build Hermitian spectrum and IFFT ----
RTF(1) = 0;  % DC forced to zero
H_full = [RTF(1); RTF(2:end)/2; conj(flipud(RTF(2:end)))/2];
h = ifft(H_full, 'symmetric');
t = (0:length(h)-1).' / Fs;

%% ---- Diagnostics ----
fprintf('IR length: %d samples (%.3f s at Fs=%d Hz)\n', length(h), length(h)/Fs, Fs);
fprintf('Max |imag|: %.2e\n', max(abs(imag(ifft(H_full)))));
fprintf('Max |h|: %.4e\n', max(abs(h)));
fprintf('Mean(h): %.4e\n', mean(h));
fprintf('Any NaN/Inf: %d\n', any(~isfinite(h)));
[~, kpk] = max(abs(h));
fprintf('Peak at: sample %d (%.1f ms)\n', kpk, (kpk-1)/Fs*1000);

%% ---- Plots ----

%% ---- Simple IR plot ----
figure('Position', [100 100 800 300]);
plot(t, h, 'b');
xlabel('Time [s]'); ylabel('Amplitude');
title('Impulse Response');
grid on;

figure('Position', [100 100 1000 700]);

% --- Plot 1: Time-domain IR with T60 decay envelope ---
subplot(3,1,1);
plot(t, h, 'b'); hold on;

delta = 3 * log(10) / T60;
[pk, kpk] = max(abs(h));
t_pk = (kpk - 1) / Fs;
env = pk * exp(-delta * (t - t_pk));
env(t < t_pk) = NaN;
plot(t, env, 'r--', 'LineWidth', 1);
plot(t, -env, 'r--', 'LineWidth', 1);

xlabel('Time [s]'); ylabel('Amplitude');
title(sprintf('Impulse response — room\\_00001, src %d, rcv %d [%.1f, %.1f, %.1f]', ...
    src_idx, rcv_idx, rx_pos));
legend('h(t)', sprintf('\\pm decay envelope, T60=%.4fs', T60), ...
    'Location', 'northeast');
grid on;

% --- Plot 2: Zoomed onset with direct-path marker ---
subplot(3,1,2);
direct_delay = norm(rx_pos - src_pos) / 343;
plot(t, h, 'b'); hold on;
xline(direct_delay, 'g--', 'direct path');
xlim([0, 0.1]);
xlabel('Time [s]'); ylabel('Amplitude');
title(sprintf('First 100 ms — direct path expected at %.1f ms', direct_delay*1000));
grid on;

% --- Plot 3: Spectrum sanity check ---
subplot(3,1,3);
H_check = fft(h);
freqs_plot = freqs_uniform;
plot(freqs_plot, 20*log10(abs(RTF) + eps), 'b', 'LineWidth', 1.2); hold on;
plot(freqs_plot, 20*log10(abs(H_check(1:K)) + eps), 'r--');
xlabel('Frequency [Hz]'); ylabel('|H(f)| [dB]');
title('Spectrum sanity check (blue: original |RTF|, red dashed: |FFT(h)|)');
legend('original |RTF|', '|FFT(h)|', 'Location', 'southwest');
grid on; xlim([0 Fs/2]);